DROP TABLE SYS_USER_ROLE;
DROP TABLE sys_role;
DROP TABLE SYS_ROLE;
DROP TABLE PERSISTENT_LOGINS;

-- 用户表 gang.wu 2019/11/20
CREATE TABLE SYS_USER(
`ID` DECIMAL(20) COMMENT '主键',
`VERSION` DECIMAL(10) DEFAULT 10 COMMENT '版本',
`CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`LOGIN_NAME` VARCHAR(255)	COMMENT '登陆名',
`NAME` VARCHAR(255) DEFAULT NULL COMMENT '旧名-可留作昵称',
`PASSWORD` VARCHAR(255) COMMENT '密码加密后',
`PHONE` VARCHAR(50) COMMENT '手机号',
 PRIMARY KEY (`ID`),
 INDEX `I_SYS_USER_LOGIN_NAME`(`LOGIN_NAME`)
);

-- 权限表 gang.wu 2019/11/20
CREATE TABLE SYS_ROLE(
`ID` DECIMAL(20) COMMENT '主键',
`VERSION` DECIMAL(10) DEFAULT 10 COMMENT '版本',
`CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`NAME` VARCHAR(255) DEFAULT NULL COMMENT '权限名',
 PRIMARY KEY (`ID`)
);

-- 用户权限表 gang.wu 2019/11/20
CREATE TABLE SYS_USER_ROLE(
`ID` DECIMAL(20) NOT NULL  COMMENT '主键',
`VERSION` DECIMAL(10) DEFAULT 10 COMMENT '版本',
`CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`USER_ID` DECIMAL(20)	COMMENT '用户ID',
`ROLE_ID` DECIMAL(20) COMMENT '权限ID',
 PRIMARY KEY (`ID`),
 CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY(`USER_ID`) REFERENCES SYS_USER(`ID`),
 CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY(`ROLE_ID`) REFERENCES SYS_ROLE(`ID`)
);

-- 忘了啥表了 gang.wu 2019/11/20
CREATE TABLE PERSISTENT_LOGINS(
`ID` DECIMAL(20) NOT NULL  COMMENT '主键',
`VERSION` DECIMAL(10) DEFAULT 10 COMMENT '版本',
`CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
`SERIES` VARCHAR(255)	COMMENT 'series',
`USERNAME` VARCHAR(255) COMMENT '用户名',
`TOKEN` VARCHAR(255) COMMENT 'token',
`LAST_USED` TIMESTAMP COMMENT '上次使用时间',
 PRIMARY KEY (`ID`),
 INDEX `I_PERSISTENT_LOGINS_TOKEN`(`TOKEN`)
);